import sys
from datetime import datetime

import _bootstrap  # noqa: F401

from app.config import PROJECT_ROOT, load_settings
from app.graph import Neo4jClient
from app.llm import LlmClient, graph_vocabulary, rows_as_json
from app.qa import Answer, answer_question

SAMPLE_QUESTIONS = (
    "Which products from Apple are supplied by TechWorld Retail?",
    "Which customers have bought Apple products?",
    "What are the top 5 best-selling products by units sold, excluding cancelled orders?",
    "Where does the word banana appear in the knowledge graph?",
    "Which customers have spent at least Rs 1,00,000, excluding cancelled orders?",
    "What did customer CU015 buy, and which vendor supplied each product?",
    "Which brands have products in cancelled orders, and how many such orders each?",
    "Which products does Sony make?",
    "What will the weather be in Mumbai tomorrow?",
)
OUTPUT = PROJECT_ROOT / "docs" / "sample_results.md"
MAX_ROWS_SHOWN = 15


def to_markdown(number: int, answer: Answer) -> str:
    parts = [f"## {number}. {answer.question}\n"]
    for rejected in answer.rejected:
        parts.append(
            f"Rejected attempt (the error was sent back to the LLM):\n```\n{rejected}\n```\n"
        )
    if answer.cypher:
        parts.append(f"Generated Cypher:\n```cypher\n{answer.cypher}\n```\n")
        shown = answer.rows[:MAX_ROWS_SHOWN]
        note = f", first {len(shown)} shown" if len(shown) < len(answer.rows) else ""
        parts.append(
            f"Retrieved rows ({len(answer.rows)}{note}):\n```json\n{rows_as_json(shown)}\n```\n"
        )
    else:
        parts.append("No query was run.\n")
    parts.append(f"**Answer:**\n\n{answer.answer}\n")
    return "\n".join(parts)


def main() -> int:
    settings = load_settings()
    llm = LlmClient(settings)
    sections = []
    with Neo4jClient(settings) as client:
        vocabulary = graph_vocabulary(client)
        for number, question in enumerate(SAMPLE_QUESTIONS, start=1):
            print(f"[{number}/{len(SAMPLE_QUESTIONS)}] {question}")
            answer = answer_question(question, client, llm, vocabulary, settings.max_result_rows)
            print(f"    {answer.answer.splitlines()[0]}")
            sections.append(to_markdown(number, answer))

    header = (
        "# Sample questions and results\n\n"
        f"Generated by `python scripts/run_sample_questions.py` on "
        f"{datetime.now():%Y-%m-%d %H:%M} with model `{settings.llm_model}`.\n"
        "Everything below is real output: the Cypher the LLM wrote, the rows Neo4j returned, "
        "and the answer written from those rows only.\n"
    )
    OUTPUT.parent.mkdir(exist_ok=True)
    OUTPUT.write_text(header + "\n" + "\n---\n\n".join(sections), encoding="utf-8")
    print(f"\nWritten to {OUTPUT.relative_to(PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
